school_name = input("Enter name of the school : ")
student_name = input("Enter name of the student : ")
roll_number = int(input("Enter roll number : "))
class_name = input("Enter class : ")
section = input("Enter section : ")
address = input("Enter address : ")
city = input("Enter city : ")
pincode = input("Enter pincode : ")
phone = input("Enter parents/ Guardian phone number : ")

print("                             school_name")
print("Student Name : ", student_name,             "Roll Number : ", roll_number)
print("Class : ", class_name,             "Section : ", section)
print("Address :     address")
print("City   : ", city,             "Pin Code : ", pincode)
print("Parents/ Guardian Contact Number contact number : phone")
